name: system_theme
description: A plugin to get the current system theme info. Supports Android, Web and Windows
version: 1.0.1
repository: https://github.com/bdlukaa/system_theme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  system_theme_web: ^0.0.2
    # path: system_theme_web/
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SystemThemePlugin
      android:
        package: com.bruno.system_theme
        pluginClass: SystemThemePlugin
      web:
        default_package: system_theme_web
